Exam_Portal/Exam_Portal/urls.py
from django.contrib import admin
from django.urls import path,include
from testapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homeView),
    path('java/', views.javaView),
    path('python/',views.pythonView),
    path('aptitude/',views.aptitudeView),
    path('accounts/logout/',views.logoutView),
    path('signup/',views.signupView),
    path('accounts/',include('django.contrib.auth.urls')),
    path('quiz/',include('quiz.urls')),
    

]

Exam_Portal/quiz/urls.py
from django.urls import path
from quiz import views

app_name = 'quiz'

urlpatterns = [
    path('', views.quiz_list, name='quiz_list'),
    path('quiz_list1/', views.quiz_list1, name='quiz_list1'),
    path('quiz_list2/', views.quiz_list2, name='quiz_list2'),
    path('quiz/<int:quiz_id>/', views.take_quiz, name='take_quiz'),
    path('quiz/<int:quiz_id>/result/', views.quiz_result, name='quiz_result'),
]

Exam_Portal/quiz/models.py
# from django.db import models
# from django.contrib.auth.models import User

# # Create your models here.
# class Quiz(models.Model):
#     title = models.CharField(max_length=255)
#     description = models.TextField()

#     def __str__(self):
#         return self.title

# class Question(models.Model):
#     quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
#     text = models.TextField()

#     def __str__(self):
#         return self.text

# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     text = models.CharField(max_length=255)
#     is_correct = models.BooleanField(default=False)

#     def __str__(self):
#         return self.text

# class UserResponse(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

#     def __str__(self):
#         return f"{self.user.username}'s response to '{self.question.text}'"

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Quiz(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.TextField()
    choice1 = models.ForeignKey('Choice', on_delete=models.CASCADE, related_name='choice1', null=True, blank=True)
    choice2 = models.ForeignKey('Choice', on_delete=models.CASCADE, related_name='choice2', null=True, blank=True)
    choice3 = models.ForeignKey('Choice', on_delete=models.CASCADE, related_name='choice3', null=True, blank=True)
    choice4 = models.ForeignKey('Choice', on_delete=models.CASCADE, related_name='choice4', null=True, blank=True)

    def __str__(self):
        return self.text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text

class UserResponse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}'s response to '{self.question.text}'"

Exam_Portal/testapp/models.py
from django.db import models

# Create your models here.

Exam_Portal/testapp/forms.py
from django import forms
from django.contrib.auth.models import User
class sighUpForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','username', 'email','password', ]

Exam_Portal/quiz/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from .models import Quiz, Question, Choice, UserResponse
from django.http import HttpResponseBadRequest
def quiz_list(request):
    quizzes = Quiz.objects.all()
    return render(request, 'quiz/quiz_list.html', {'quizzes': quizzes})

def quiz_list1(request):
    quizzes = Quiz.objects.all()
    return render(request, 'quiz/quiz_list1.html', {'quizzes': quizzes})


def quiz_list2(request):
    quizzes = Quiz.objects.all()
    return render(request, 'quiz/quiz_list2.html', {'quizzes': quizzes})

def take_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    questions = Question.objects.filter(quiz=quiz)
    return render(request, 'quiz/take_quiz.html', {'quiz': quiz, 'questions': questions})

def quiz_result(request, quiz_id):
    if request.method == 'POST':
        user = request.user
        quiz = get_object_or_404(Quiz, pk=quiz_id)
        score = 0
        total_questions = 0
        for question in quiz.question_set.all():
            total_questions += 1
            choice_id = request.POST.get(f'question_{question.id}')
            if choice_id:
                choice = get_object_or_404(Choice, pk=choice_id)
                if choice.is_correct:
                    score += 1
                UserResponse.objects.create(user=user, question=question, choice=choice)
        percentage = (score / total_questions) * 100
        return render(request, 'quiz/quiz_result.html', {'quiz': quiz, 'score': score, 'total_questions': total_questions, 'percentage': percentage})
    else:
        return HttpResponseBadRequest()

Exam_Portal/testapp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from testapp.forms import *  
from django.http import HttpResponseRedirect
from django.contrib.auth import logout
from django.shortcuts import redirect

# Create your views here.
def homeView(request):
    return render(request, 'pages/home.html')

@login_required
def javaView(request):
    return render(request, 'pages/java.html')

@login_required
def pythonView(request):
    return render(request, 'pages/python.html')

@login_required
def aptitudeView(request):
    return render(request, 'pages/Aptitude.html')

def logoutView(request):
    logout(request)
    return redirect('/')

def signupView(request):
    form = sighUpForm()
    if request.method == 'POST':
        form = sighUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.set_password(user.password)
            user.save()
            return HttpResponseRedirect('/accounts/login')
    return render(request, 'pages/signup.html', {'form': form})

Exam_Portal/templates/pages/Aptitude.html
{% extends 'pages/base.html'%}
{% block content %}
{% include 'pages/navbar.html' %}
<div class="card-panel grey lighten-2" style="margin-top:200px;">
    <h1 class="center-align">Aptitude exams</h1>
</div>
{% endblock %}

Exam_Portal/templates/pages/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
</head>
<body>
    
    {% block content %}{% endblock %}
    {% block script %}{% endblock %} 
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>  
    <script src="{% static 'js/materialize.min.js' %}"></script>  
</body>
</html>

Exam_Portal/templates/pages/home.html
{% extends 'pages/base.html' %}

{% block style %}
<style>
    .container {
        margin-top: 50px;
        text-align: start;
    }    
</style>
{% endblock %}

{% block content %}
{% include 'pages/navbar.html' %}
<div class="container" style="margin-top:50px;">
    <div class="row s12">
        <div class="col s12">
            <ul class="grey-text">
                <li>Ensure secure authentication and role-based authorization</li>
                <li>Implement measures like browser lockdown and answer randomization</li>
                <li>Set a time limit for exam completion to maintain fairness</li>
                <li>Randomize question and answer order to deter cheating</li>
                <li>Allow students to review and receive feedback on their answers</li>
                <li>Automate grading processes for efficiency</li>
                <li>Prevent access to external resources during exams</li>
                <li>Protect student data and ensure compliance with privacy regulations</li>
            </ul>            
        </div>
    </div>
</div>
<div class="card-panel yellow lighten-1">
  {% if user.is_authenticated %}
  <span class="center-align">
    <h5 class="flow-text">
      Welcome to TechTechArena! Start exploring quizzes to enhance your skills
    </h5>
  </span>
  {% else %}
  <span class="center-align">
    <h5 class="flow-text">
      Explore quizzes and expand your skills at TechTechArena! Sign up today
      <a class="waves-effect black waves-light btn"><i class="material-icons right">arrow_forward</i>sign up</a>
    </h5>
  </span>
  {% endif %}
</div>

<footer class="black page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="green-text">Available Quiz</h5>
          <p class="grey-text text-lighten-4">Java</p>
          <p class="grey-text text-lighten-4">Python</p>
          <p class="grey-text text-lighten-4">Aptitude</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="green-text">Follow me!</h5>
          <ul class="icons">
            <li>
              <a class="grey-text text-lighten-3" href="#!">
                <i class="fab fa-linkedin-in social-icon"></i>
              </a>
            </li>  
            <li>
              <a class="grey-text text-lighten-3" href="#!">
                <i class="fab fa-github social-icon"></i>
              </a>
            </li>             
            <li>
              <a class="grey-text text-lighten-3" href="#!">
                <i class="fab fa-facebook-f social-icon"></i>
              </a>
            </li>
            <li>
              <a class="grey-text text-lighten-3" href="#!">
                <i class="fab fa-instagram social-icon"></i>
              </a>
            </li>            
          </ul>
        </div>
      </div>
    </div>
    <div class="grey darken-3 footer-copyright">
      <div class="container">
        <p class="center-align">© 2014 TechTestArena</p>
      </div>
    </div>
  </footer>
<style>
    li{
        padding: 10px;
        font-size:20px;
    }
    .icons li{
      display:inline-block;
      padding: 5px;
      font-size:18px;
    }
    .icons li:hover{
      opacity: 0.1;
    }
     
    body{
      background-color:black;
    }
    .waves-effect:hover{
      opacity:0;
    }
</style>
{% endblock %}

Exam_Portal/templates/pages/java.html
{% extends 'pages/base.html'%}
{% block content %}
{% include 'pages/navbar.html' %}
<div class="card-panel teal lighten-2" style="margin-top:200px;">
    <h1 class="center-align">java exams</h1>
</div>
{% endblock %}

Exam_Portal/templates/pages/logout.html
{% extends 'pages/base.html'%}
{% block content %}
<div class="container" style="margin-top:200px;">
    <div class="row s12">
        <div class="col s12">
            <h4 class="red-text">logout successfully</h4>
            <br>
            {% comment %} <a  class="waves-effect green waves-light btn" href="/accounts/login">Login Again!</a> {% endcomment %}
        </div>
    </div>
</div>
<style>
    .container{
         display:flex;
         justify-content:center;
         align-items:center;
 
    }
</style>
{% endblock %}

Exam_Portal/templates/pages/navbar.html
{% extends 'pages/base.html' %}


{% block content %}
<nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo black-text">&nbsp;&nbsp;TechTestArena</a>
      <a href="/" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        {% if user.is_authenticated %}
        <li><a href="{% url 'quiz:quiz_list' %}">Java</a></li>
        <li><a href="{% url 'quiz:quiz_list1' %}">python</a></li>
        <li><a href="{% url 'quiz:quiz_list2' %}">Aptitude</a></li>
        <li><a href="/accounts/logout">Logout</a></li>
        {% else %}
            <li><a href="/accounts/login">Login</a></li>
            <li><a href="/signup">Sign Up</a></li>
        {% endif %}
      </ul>
    </div>
</nav>
<ul class="sidenav" id="mobile-demo">
    {% if user.is_authenticated %}
    <li><a href="{% url 'quiz:quiz_list' %}">Java</a></li>
    <li><a href="{% url 'quiz:quiz_list1' %}">python</a></li>
    <li><a href="{% url 'quiz:quiz_list2' %}">Aptitude</a></li>
    <li><a href="/accounts/logout">Logout</a></li>
    {% else %}
        <li><a href="/accounts/login">Login</a></li>
        <li><a href="/signup">Sign Up</a></li>
    {% endif %}
</ul>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.sidenav');
        var instances = M.Sidenav.init(elems);
    });    
</script>
<style>
    nav {
        background-color: #007bff; /* Change the background color to your desired color */
    }

    nav ul.right li a {
        font-size: 20px !important;
    }
    
    nav ul.right li a:hover {
        text-decoration: none;
        opacity: 0;
        background: none !important;
    }
</style>
{% endblock %}

Exam_Portal/templates/pages/python.html
{% extends 'pages/base.html'%}
{% block content %}
{% include 'pages/navbar.html' %}
<div class="card-panel red lighten-4" style="margin-top:200px;">
    <h1 class="center-align">python exams</h1>
</div>
{% endblock %}

Exam_Portal/templates/pages/signup.html
{% extends 'pages/base.html'%}

{% block content %}
{% include 'pages/navbar.html' %}
<div class="container container-sm" style="margin-top:50px;">
    <h3 class="center-align">Sign Up</h3>
    <div class="row s12 m6">
        <form method="post">
            {{form}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>
</div>
{% endblock %} 

Exam_Portal/templates/quiz/quiz_list.html
{% extends 'pages/base.html' %}
{% block content %}
    <div class="container" style="margin-top:120px;">
        <div class="row s12">
            <div class="col s12  m6 offset-m3">
                {% for quiz in quizzes %}
                    {% if quiz.title == 'javaQuiz' %}
                    <h5 class="teal-text">{{ quiz.title }}</h5>
                    <p>{{ quiz.description }}</p>
                    <a  href="{% url 'quiz:take_quiz' quiz.id %}">Take Quiz</a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock%}

Exam_Portal/templates/quiz/quiz_list1.html
{% extends 'pages/base.html' %}
{% block content %}
    <div class="container" style="margin-top:120px;">
        <div class="row s12">
            <div class="col s12  m6 offset-m3">
                {% for quiz in quizzes %}
                    {% if quiz.title == 'pythonQuiz' %}
                    <h5 class="teal-text">{{ quiz.title }}</h5>
                    <p>{{ quiz.description }}</p>
                    <a href="{% url 'quiz:take_quiz' quiz.id %}">Take Quiz</a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock%}

Exam_Portal/templates/quiz/quiz_list2.html
{% extends 'pages/base.html' %}
{% block content %}
    <div class="container" style="margin-top:120px;">
        <div class="row s12">
            <div class="col s12  m6 offset-m3">
                {% for quiz in quizzes %}
                    {% if quiz.title == 'AptitudeQuiz' %}
                    <h5 class="teal-text">{{ quiz.title }}</h5>
                    <p>{{ quiz.description }}</p>
                    <a href="{% url 'quiz:take_quiz' quiz.id %}">Take Quiz</a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock%}

Exam_Portal/templates/quiz/quiz_result.html
{% extends 'pages/base.html' %}
{% block content %}
<div class="container">
    <div class="row s12">
        <div class="col s12">
            <h2 class="green-text">Quiz Result</h2>
            <h5 class="blue-text">Score: {{ score }}/{{ total_questions }}</h5>
            <h6 class="pink-text">Percentage: {{ percentage }}%</h6>
            <br>
            <a href="/" class="waves-effect waves-light btn">Continue Practice</a>
        </div>
    </div>
</div>
<style>
    .container {
        margin-top: 120px;
        display:flex;
        justify-content:center;
        align-items:center;
    }
</style>
{% endblock %}

Exam_Portal/templates/quiz/take_quiz.html
{% extends "pages/base.html" %}
{% block content %}
<div class="container" style="margin-top:120px;">
    <div class="row s12">
        <div class="col s12">
            <form method="post" action="{% url 'quiz:quiz_result' quiz.id %}">
                {% csrf_token %}
                {% for question in questions %}
                    <h5 class="green-text">{{ question.text }}</h5>
                    {% for choice in question.choice_set.all %}
                    <p>
                    <label>
                        <input name="question_{{ question.id }}" value="{{ choice.id }}" type="radio" />
                        <span class="blue-text">{{ choice.text }}</span>
                    </label>
                    </p>
                    {% endfor %}
                {% endfor %}
                <button class="waves-effect waves-light btn" type="submit">Submit</button>
              </form>
        </div>
    </div>
</div>
<style>
    .container{
        display:flex;
        justify-content:center;
        align-items:center;
    }
</style>
{% endblock %}